import React from "react";

import {
  Box,
  Container,
  Divider,
  Grid,
  ListItemText,
  Rating,
  Toolbar,
  Typography,
  Button,
  Stack,
} from "@mui/material";
import Head from "next/head";

import AddShoppingCartIcon from "@mui/icons-material/AddShoppingCart";
import KeyboardBackspaceIcon from "@mui/icons-material/KeyboardBackspace";
import Image from "next/image";

function Product({ product }) {
  const listStyle = {
    display: "flex",
    flexDirection: "column-reverse",
    ".MuiListItemText-primary": {
      fontSize: "1.25rem",
      fontWeight: 500,
    },
    ".MuiListItemText-secondary": {
      color: "#4093a3",
      fontWeight: 400,
      fontSize: "1rem",
    },
  };

  const listStyleTwo = {
    display: "flex",
    // alignItems: "center",
    ".MuiListItemText-primary": {
      fontSize: "1.5rem",
      fontWeight: 400,
    },
    ".MuiListItemText-secondary": {
      color: "rgba(22,29,37, 0.3)",
      fontWeight: 400,
      fontSize: "1.25rem",
      textDecoration: "line-through",
      paddingX: "0.4rem",
    },
  };

  console.table(product);
  return (
    <div>
      <Head>
        <title>Dev By Nate | E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Toolbar />
        <Container sx={{ paddingY: { xs: "1rem", md: "3rem" } }}>
          <Grid container sx={{ height: { xs: "100vh", md: "60vh" } }}>
            <Grid
              item
              xs={12}
              md={5}
              sx={{
                padding: { md: "1rem" },
                height: { xs: "18rem", md: "100%" },
              }}
            >
              <Box
                sx={{
                  width: "100%",
                  height: "100%",
                  background: "white",
                  position: "relative",
                }}
              >
                <Image
                  src={product.image}
                  alt={product.title}
                  fill
                  style={{ objectFit: "contain" }}
                />
              </Box>
            </Grid>
            <Grid item xs={12} md={7} sx={{ padding: { md: "1rem" } }}>
              <Box
                sx={{ width: "100%", background: "", paddingBottom: "0.8rem" }}
              >
                <ListItemText
                  sx={listStyle}
                  primary={product.title}
                  secondary={product.category}
                />
                <Rating
                  name="product rating"
                  value={product.rating.rate}
                  size="small"
                  readOnly
                  sx={{ paddingX: 0 }}
                  precision={0.5}
                />
                <Divider />
              </Box>

              <Grid container>
                <Grid
                  item
                  xs={12}
                  md={6}
                  lg={8}
                  sx={{ padding: "0.5rem", paddingRight: "1rem" }}
                >
                  <Typography variant="body1">{product.description}</Typography>
                </Grid>
                <Grid item xs={12} md={6} lg={4} sx={{ padding: "0.5rem" }}>
                  <Stack>
                    <Stack
                      direction="row"
                      justifyContent="space-between"
                      alignItems="center"
                    >
                      <ListItemText sx={listStyleTwo} primary={product.price} />
                      <Typography variant="body1">Quantity</Typography>
                    </Stack>
                    <Box sx={{ paddingY: "0.5rem" }}>
                      <Button
                        variant="contained"
                        disableElevation
                        sx={{
                          background: "rgba(245,167,70, 0.8)",
                          width: "100%",
                          textTransform: "capitalize",
                          fontWeight: 400,
                          marginY: "0.2rem",
                          "&:hover": {
                            background: "#f3a846",
                          },
                        }}
                        // color=""
                        startIcon={<AddShoppingCartIcon />}
                      >
                        Add to Cart
                      </Button>
                      <Button
                        variant="outlined"
                        disableElevation
                        sx={{
                          border: "2px solid #252d33",
                          width: "100%",
                          textTransform: "capitalize",
                          fontWeight: 400,
                          color: "#252d33",
                          marginY: "0.2rem",
                          "&:hover": {
                            // background: "#f3a846",
                            border: "2px solid #f3a846",
                          },
                        }}
                        // color=""
                        startIcon={<KeyboardBackspaceIcon />}
                      >
                        Continue Shopping
                      </Button>
                    </Box>
                  </Stack>
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  );
}

export default Product;

export async function getStaticProps({ params }) {
  const res = await fetch(`https://fakestoreapi.com/products/${params.id}`);
  const results = await res.json();

  return {
    props: {
      product: results[0],
    },
  };
}

// export async function getStaticPaths() {
//   const res = await fetch("https://fakestoreapi.com/products");
//   const products = await res.json();

//   const paths = products.map((product) => {
//     return {
//       params: {
//         id: product.id,
//       },
//     };
//   });

//   return {
//     paths,
//     fallback: false,
//   };
// }
